class Autogenerated {
  int? statusCode;
  String? message;
  Result? result;

  Autogenerated({this.statusCode, this.message, this.result});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    statusCode = json['status_code'];
    message = json['message'];
    result =
        json['result'] != null ? new Result.fromJson(json['result']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status_code'] = this.statusCode;
    data['message'] = this.message;
    if (this.result != null) {
      data['result'] = this.result!.toJson();
    }
    return data;
  }
}

class Result {
  String? cATEGORY;
  String? tITLE;
  String? cONTENT;
  String? vIEWCOUNT;
  String? qUESTIONIMAGE;
  int? cOUNTANSWER;
  List<ANSWER>? aNSWER;
  String? cREATOR;
  String? cREATEDDTTM;
  Null? uPDATEDDTTM;

  Result(
      {this.cATEGORY,
      this.tITLE,
      this.cONTENT,
      this.vIEWCOUNT,
      this.qUESTIONIMAGE,
      this.cOUNTANSWER,
      this.aNSWER,
      this.cREATOR,
      this.cREATEDDTTM,
      this.uPDATEDDTTM});

  Result.fromJson(Map<String, dynamic> json) {
    cATEGORY = json['CATEGORY'];
    tITLE = json['TITLE'];
    cONTENT = json['CONTENT'];
    vIEWCOUNT = json['VIEW_COUNT'];
    qUESTIONIMAGE = json['QUESTION_IMAGE'];
    cOUNTANSWER = json['COUNT_ANSWER'];
    if (json['ANSWER'] != null) {
      aNSWER = <ANSWER>[];
      json['ANSWER'].forEach((v) {
        aNSWER!.add(new ANSWER.fromJson(v));
      });
    }
    cREATOR = json['CREATOR'];
    cREATEDDTTM = json['CREATED_DTTM'];
    uPDATEDDTTM = json['UPDATED_DTTM'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['CATEGORY'] = this.cATEGORY;
    data['TITLE'] = this.tITLE;
    data['CONTENT'] = this.cONTENT;
    data['VIEW_COUNT'] = this.vIEWCOUNT;
    data['QUESTION_IMAGE'] = this.qUESTIONIMAGE;
    data['COUNT_ANSWER'] = this.cOUNTANSWER;
    if (this.aNSWER != null) {
      data['ANSWER'] = this.aNSWER!.map((v) => v.toJson()).toList();
    }
    data['CREATOR'] = this.cREATOR;
    data['CREATED_DTTM'] = this.cREATEDDTTM;
    data['UPDATED_DTTM'] = this.uPDATEDDTTM;
    return data;
  }
}

class ANSWER {
  int? aNSWERID;
  int? qUESTIONID;
  String? cONTENT;
  Null? aNSWERIMAGE;
  String? cREATOR;
  String? cREATEDDTTM;
  Null? uPDATEDDTTM;

  ANSWER(
      {this.aNSWERID,
      this.qUESTIONID,
      this.cONTENT,
      this.aNSWERIMAGE,
      this.cREATOR,
      this.cREATEDDTTM,
      this.uPDATEDDTTM});

  ANSWER.fromJson(Map<String, dynamic> json) {
    aNSWERID = json['ANSWER_ID'];
    qUESTIONID = json['QUESTION_ID'];
    cONTENT = json['CONTENT'];
    aNSWERIMAGE = json['ANSWER_IMAGE'];
    cREATOR = json['CREATOR'];
    cREATEDDTTM = json['CREATED_DTTM'];
    uPDATEDDTTM = json['UPDATED_DTTM'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['ANSWER_ID'] = this.aNSWERID;
    data['QUESTION_ID'] = this.qUESTIONID;
    data['CONTENT'] = this.cONTENT;
    data['ANSWER_IMAGE'] = this.aNSWERIMAGE;
    data['CREATOR'] = this.cREATOR;
    data['CREATED_DTTM'] = this.cREATEDDTTM;
    data['UPDATED_DTTM'] = this.uPDATEDDTTM;
    return data;
  }
}
